const questions=[
{t:'Metagaming',q:'Durante uma perseguição, um amigo fora do jogo envia pelo Discord a localização exata do suspeito. Você pode usar essa informação?',o:['Sim, porque ajuda a corporação.','Não. É informação externa ao RP e caracteriza Metagaming.','Sim, desde que nenhum administrador veja.','Somente se eu estiver em perseguição.'],a:1},
{t:'Hierarquia',q:'Seu comandante determina recuo, mas você acredita que conseguiria prender o suspeito avançando sozinho. O que faz?',o:['Avanço sozinho.','Ignoro a ordem se estiver perto do suspeito.','Cumpro o recuo e, em momento adequado, comunico minha avaliação ao superior.','Peço para outro policial avançar no meu lugar.'],a:2},
{t:'Conduta',q:'Um membro da CHOQUE quebra uma regra e isso beneficia sua equipe. Qual é a melhor conduta?',o:['Ignorar porque beneficiou a equipe.','Incentivar a repetir.','Preservar o RP e reportar a situação pelos meios adequados após controlar a ocorrência.','Discutir com ele imediatamente no meio da ação.'],a:2},
{t:'Refém',q:'Há um criminoso armado mantendo um refém. Um membro quer iniciar ação imediatamente. Qual é a prioridade?',o:['Atirar o mais rápido possível.','Preservar vidas, avaliar riscos e seguir negociação/comando antes de uma intervenção.','Entrar sozinho para surpreender.','Abandonar a ocorrência.'],a:1},
{t:'Comunicação',q:'Vários policiais falam ao mesmo tempo no rádio durante uma perseguição. Como agir?',o:['Falar ainda mais alto.','Desligar o rádio.','Organizar comunicações curtas, objetivas e priorizar informações essenciais.','Usar Discord para continuar falando.'],a:2},
{t:'Amor à vida',q:'Qual opção representa melhor o princípio de amor à vida?',o:['Sempre enfrentar qualquer risco.','Valorizar a sobrevivência do personagem e evitar atitudes irreais/desnecessariamente suicidas.','Nunca participar de confronto.','Fugir de toda abordagem.'],a:1},
{t:'Tomada de decisão',q:'Sua equipe está em clara desvantagem e avançar pode comprometer todos. O comandante ainda não ordenou recuo. O que é mais adequado?',o:['Avançar sem comunicar.','Abandonar a equipe.','Comunicar a avaliação de risco, buscar orientação e adotar posição segura conforme a situação.','Desconectar do servidor.'],a:2},
{t:'Civis',q:'Um suspeito foge para uma região cheia de civis. Qual deve ser a preocupação principal?',o:['Capturar a qualquer custo.','Reduzir riscos aos civis e à equipe, adaptando a abordagem à situação.','Atirar para assustar os civis.','Encerrar o RP imediatamente.'],a:1},
{t:'Disciplina',q:'Você considera injusta uma punição interna aplicada por um superior. Como deve reagir?',o:['Ofender o superior.','Sair da corporação imediatamente.','Manter respeito e apresentar sua versão pelos canais internos apropriados.','Criar discussão no rádio durante uma ocorrência.'],a:2},
{t:'Situação crítica',q:'Companheiro ferido, civis próximos, suspeito fugindo, rádio congestionado e sem contato com comandante. Qual resposta demonstra melhor prioridade?',o:['Ignorar todos e perseguir o suspeito.','Avaliar ameaças imediatas, proteger vidas, buscar apoio/comunicação e só então continuar a ação conforme segurança e regras.','Atirar no suspeito independentemente do risco.','Esperar parado até o comandante responder.'],a:1}
];
let i=0,respostas=Array(questions.length).fill(null);const $=s=>document.querySelector(s);function show(){let q=questions[i];$('#counter').textContent=`Questão ${i+1} de ${questions.length}`;$('#pct').textContent=`${(i+1)*10}%`;$('#bar').style.width=`${(i+1)*10}%`;$('#qtitle').textContent=`${String(i+1).padStart(2,'0')} — ${q.t}`;$('#qtext').textContent=q.q;$('#answers').innerHTML=q.o.map((x,n)=>`<div class="option ${respostas[i]===n?'selected':''}" data-n="${n}">${x}</div>`).join('');document.querySelectorAll('.option').forEach(el=>el.onclick=()=>{respostas[i]=+el.dataset.n;show()});$('#prev').style.visibility=i?'visible':'hidden';$('#next').textContent=i===questions.length-1?'FINALIZAR':'PRÓXIMA'}
$('#start').onclick=()=>{if(!$('#nome').value.trim()||!$('#pid').value.trim()||!$('#idade').value||!$('#discord').value.trim())return alert('Preencha todos os dados do candidato.');$('#intro').classList.add('hidden');$('#quiz').classList.remove('hidden');show()};$('#prev').onclick=()=>{if(i){i--;show()}};$('#next').onclick=()=>{if(respostas[i]===null)return alert('Selecione uma resposta.');if(i<questions.length-1){i++;show();return}finish()};function finish(){let acertos=respostas.reduce((s,r,n)=>s+(r===questions[n].a),0),score=acertos*10,ok=score>=70;$('#quiz').classList.add('hidden');let r=$('#result');r.classList.remove('hidden');r.innerHTML=`<span class='tag'>RESULTADO DO EDITAL</span><h2 class='${ok?'result-ok':'result-no'}'>${ok?'✅ APROVADO':'❌ REPROVADO'}</h2><p>Candidato: <b>${escapeHtml($('#nome').value)}</b> • ID ${escapeHtml($('#pid').value)}</p><div class='score'>${score}/100</div><p>${ok?'Parabéns! Você atingiu a nota mínima da primeira fase. Aguarde as próximas orientações da equipe responsável.':'Você não atingiu a nota mínima de 70 pontos. Revise as regras e procedimentos antes de uma nova tentativa.'}</p><button onclick='location.reload()'>NOVA INSCRIÇÃO</button>`}function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
